stages:
  - deploy

deploy:
  stage: deploy
  image: node:16
  variables:
    SSH_DEST_DEV: forge@10.0.0.3:/var/www/devapps/front.klinikatech.com/
    SSH_DEST_STAGING: forge@10.0.0.3:/var/www/front.klinikatech.com/
    SSH_DEST_MAIN: root@10.0.0.2:/var/www/new.klinikatech.com/
  when: manual
  only:
    - main
    - staging
    - dev
  before_script:
    - |
      which ssh-agent || ( apt-get update -y && apt-get install openssh-client coreutils -y --no-install-recommends )
      eval $(ssh-agent -s)
      echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
      mkdir -pv ~/.ssh
      if [[ -f /.dockerenv ]]; then
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      fi
      echo "10.0.0.5        https://gitlab.klinikatech.com" >> /etc/hosts
  script:
    - apt-get update -y
    - apt-get install -y rsync
    - npm install
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then npm run build:prod; elif [ "$CI_COMMIT_BRANCH" = "staging" ];then npm run build:staging; else npm run build:dev; fi
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then rsync -avz --del ./build/ $SSH_DEST_MAIN; elif [ "$CI_COMMIT_BRANCH" = "stage" ];then rsync -avz --del ./build/ $SSH_DEST_STAGING; else rsync -avz --del ./build/ $SSH_DEST_DEV; fi
    - ssh root@10.0.0.2 "rsync -vraz --delete --chmod=g+w  /var/www/new.klinikatech.com/ 10.0.0.9:/var/www/new.klinikatech.com/"
