stages:
  - deploy

deploy:
  stage: deploy
  image: node:14
  variables:
    SSH_DEST_STAGING: forge@159.65.124.162:/var/www/front.klinikatech.com/
    SSH_DEST_MAIN: forge@159.65.117.211:/var/www/new.klinikatech.com/
  when: manual
  only:
    - main
    - staging
  before_script:
    - |
      which ssh-agent || ( apt-get update -y && apt-get install openssh-client coreutils -y --no-install-recommends )
      eval $(ssh-agent -s)
      echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
      mkdir -pv ~/.ssh
      if [[ -f /.dockerenv ]]; then
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      fi
  script:
    - apt-get update -y
    - apt-get install -y rsync
    - npm install
    - npm run build:dev
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then rsync -avz --del ./build/ $SSH_DEST_MAIN; else rsync -avz --del ./build/ $SSH_DEST_STAGING; fi
