
const ResourceLins = {
    Region:'/dashboard/regions/',
    Country:'/dashboard/countries/',
    City:'/dashboard/cities/',
    Category:'/dashboard/categories/',
    SubCategory:'/dashboard/sub-categories/',
    Service:'/dashboard/services/',
    SubService:'/dashboard/sub-services/',
    NursingTask:'/dashboard/nursing-tasks/',
    LabPackage:'/dashboard/lab-packages/',
    LabPackageCategory:'/dashboard/lab-packages-category/',
    LabTestCategory:'/dashboard/lab-tests-category/',
    LabTest:'/dashboard/lab-tests/',
    Taxonomy:'/dashboard/taxonomies/',
    InsuranceCompany:'/dashboard/insurance-companies/',
    PaymentMethod:'/dashboard/payment-methods/',
    Role:'/dashboard/roles/',
    BugReport:'/dashboard/bug-reports/',
    Specialty:'/dashboard/specialties/',
    SubSpecialty:'/dashboard/sub-specialties/',
    Doctor:'/dashboard/doctors/',
    User:'/dashboard/users/',
    Post:'/dashboard/posts/',
    Clinic:'/dashboard/clinics/',
    Offer:'/dashboard/offers/',
    Coupon:'/dashboard/coupons/',
    ClinicDoctor:'/dashboard/clinics/doctors/',
    ClinicWorkingHours:'/dashboard/clinics/working-hours/',
    ClinicLabTest:'/dashboard/clinics/lab-tests/',
    ClinicLabPackage:'/dashboard/clinics/lab-packages/',
    ClinicDoctorWorkingHours:'/dashboard/clinic-doctors/working-hours/',

}
export default ResourceLins
